In [6]:
#| echo: false

import itertools
import math
import numpy as np

# Combinatorics

[Open in Colab](https://colab.research.google.com/github/febse/stat2024/blob/main/04-Combinatorics.ipynb)

While counting things may seem simple, it can become quite when the number of things to count grows. For example, consider the following problem:

As the example of the garden of forking data shows, we need to be able to count the number of ways to choose a subset of elements from a set. This is the subject of combinatorics and there are four basic formulas that we will use to solve these problems.

## The Counting Principle

In the garden of forking data we needed to count the number of ways a collection of three white and one blue balls could produce samples three balls, selected with replacement. 

The first selected ball can be any of the four balls in the box and there are four possibilities. The second selected ball can also be any of the four balls in the box and there are again four possibilities.

Up to now we have a total of $4 \times 4 = 16$ possibilities. The last selected balls can also be any of the four balls in the box and there are four possibilities. The total number of possibilities is $4 \times 4 \times 4 = 64$.

More generally, there are $n^s$ ways to select $s$ elements from a set of $n$ elements, with replacement.

Even more generally, consider a DJ who has a set of $m_s$ salsa songs, $m_b$ bachata songs and $m_r$ reggaeton songs. The DJ plans to play a set of three songs, each of a different genre. How many possible sets of songs can the DJ play?

- There are $m_s$ ways to select a salsa song.
- There are $m_b$ ways to select a bachata song.
- There are $m_r$ ways to select a reggaeton song.

The total number of possible sets of songs is $m_s \times m_b \times m_r$.


In [7]:
# An example: all possible 3-song playlists where the first sort is a salsa song, the second a bachata song, and the third a reggaeton song.

m_s = 200 # Salsa songs
m_b = 80 # Bachata songs
m_r = 100 # Reggaeton songs

m_s * m_b * m_r

1600000



## Permutations

A permutation is an arrangement of objects in a specific order. If we have a set of $n$ (distinct) objects and we want to arrange them in a specific order, there are $n!$ ways to do this. The factorial function is defined as:

$$
n! = n \times (n-1) \times (n-2) \times \ldots \times 2 \times 1
$$

How to explain this formula? Let's set $n = 5$ and consider a set of five songs that a DJ wants to play in sequence. The first song can be any of the five songs, the second song can be any of the remaining four songs, the third song can be any of the remaining three songs, and so on. The total number of ways to arrange the songs is $5 \times 4 \times 3 \times 2 \times 1 = 5! = 120$.


In [8]:
# To compute the factorial you can use the factorial function from the math module (which is imported here at the top of the notebook). 

math.factorial(5)

120


:::{#exm-permutations}
## Permutations

You have 4 books on your shelf at home. In how many ways can you arrange them?

:::


In [9]:
# Create a list of 3 books

books3 = ["Framed", "Malas", "Ellipses"]

print("The number of possible arrangements is 3! = 3*2*1 = 6")
print("Check it out:", math.factorial(3))

print("All possible arrangements of the books:")

# NOTE: code for illustration only
# Generate all permutations of the books in the list above and print them
for p in itertools.permutations(books3):
    print(p)


The number of possible arrangements is 3! = 3*2*1 = 6
Check it out: 6
All possible arrangements of the books:
('Framed', 'Malas', 'Ellipses')
('Framed', 'Ellipses', 'Malas')
('Malas', 'Framed', 'Ellipses')
('Malas', 'Ellipses', 'Framed')
('Ellipses', 'Framed', 'Malas')
('Ellipses', 'Malas', 'Framed')


In [10]:
# We can repeat this for a list of 4 books

books4 = ["Framed", "Malas", "Ellipses", "Beautiful Days"]

print("The number of possible arrangements is 4! = 4*3*2*1 = 24")
print("Compare it with the result from math.factorial:", math.factorial(4))

print("All possible arrangements of the books:")

# NOTE: # NOTE: code for illustration only
for p in itertools.permutations(books4):
    print(p)

The number of possible arrangements is 4! = 4*3*2*1 = 24
Compare it with the result from math.factorial: 24
All possible arrangements of the books:
('Framed', 'Malas', 'Ellipses', 'Beautiful Days')
('Framed', 'Malas', 'Beautiful Days', 'Ellipses')
('Framed', 'Ellipses', 'Malas', 'Beautiful Days')
('Framed', 'Ellipses', 'Beautiful Days', 'Malas')
('Framed', 'Beautiful Days', 'Malas', 'Ellipses')
('Framed', 'Beautiful Days', 'Ellipses', 'Malas')
('Malas', 'Framed', 'Ellipses', 'Beautiful Days')
('Malas', 'Framed', 'Beautiful Days', 'Ellipses')
('Malas', 'Ellipses', 'Framed', 'Beautiful Days')
('Malas', 'Ellipses', 'Beautiful Days', 'Framed')
('Malas', 'Beautiful Days', 'Framed', 'Ellipses')
('Malas', 'Beautiful Days', 'Ellipses', 'Framed')
('Ellipses', 'Framed', 'Malas', 'Beautiful Days')
('Ellipses', 'Framed', 'Beautiful Days', 'Malas')
('Ellipses', 'Malas', 'Framed', 'Beautiful Days')
('Ellipses', 'Malas', 'Beautiful Days', 'Framed')
('Ellipses', 'Beautiful Days', 'Framed', 'Malas')
('

:::{#exr-permutations}
## Permutations

A small company has 16 employees. They want to line up for a group photo. In how many ways can they arrange themselves?

:::

In [11]:
math.factorial(16)

20922789888000

In [12]:
# NOTE: code for illustration only. The code here only prettifies the large number (16!) so that we can read it more easily. You don't need to remember the syntax.

print(f"{math.factorial(16):,}")
print(f"{math.factorial(16):e}")

20,922,789,888,000
2.092279e+13


In [13]:
# To make some sense of this large number, let's say that the employees are very fast and can 
# make a photo of each arrangement 10 milliseconds. How many years would it take to make all the photos?

10 * math.factorial(16) / 60 / 60 / 24 / 365

6634573.150684931

In [15]:
# Let's say that half of the members of parliament take a group photo. How many arrangements of 120 people are there?

print(f"{math.factorial(120):e}")

6.689503e+198


It is hard to imagine the magnitude of extremely large numbers such as $120!$ for example. To gain some perspective, take a look at the following short documentary (it goes to $10^{26}$).

{{< video https://www.youtube.com/embed/44cv416bKP4?si=yzDHrjd0xuKCVtCm
    title="Scales of the Universe in Powers of Ten"
>}}

## k-permutations

The empoyees of our small company decide that it would take too long to go through all the possible group photo arrangements. They decide to take a group photo with only 5 employees. In how many ways can they arrange themselves?

Again, think about the group photo as having five slots. The first slot can be filled by any of the 16 employees, the second slot can be filled by any of the remaining 15 employees, and so on.

The total number of ways to arrange the employees is 

$$
\underbrace{16}_{\text{Slot 1}} \times \underbrace{15}_{\text{Slot 2}} \times \underbrace{14}_{\text{Slot 3}} \times \underbrace{13}_{\text{Slot 4}} \times \underbrace{12}_{\text{Slot 5}} = 16 \times 15 \times 14 \times 13 \times 12 = 524160
$$

In [10]:
16 * 15 * 14 * 13 * 12

524160

More generally, we can arrange $k$ elements from a set of $n$ elements in 

$$ 
n \times (n-1) \times \ldots \times (n-(k - 1))
$$

ways. In the previous example we had $n = 16$ and $k = 5$.

$$
(16 - \underbrace{0}_{5 - 5}) \times (16 - \underbrace{1}_{5 - 4}) \times (16 - \underbrace{2}_{5 - 3}) \times (16 - \underbrace{3}_{5 - 2}) \times (16 - \underbrace{4}_{5 - 1}) = 16 \times 15 \times 14 \times 13 \times 12 = 524160
$$

Usually we write this in a more compact form:

$$
\frac{16!}{(16-5)!} = \frac{16!}{11!} = \frac{16 \times 15 \times 14 \times 13 \times 12 \times \cancel{11!}}{\cancel{11!}}
$$

Or more generally there are 

$$
\frac{n!}{(n - k)!}
$$

ways to arrange $k$ elements from a set of $n$ elements.


In [11]:
math.factorial(16) / math.factorial(11)

524160.0

## Combinations

There are occasions when we are not interested in the order of the elements in a subset. For example, the employees of the small company may not care about the order in which they are arranged in the group photo, only that they are in the photo. How many arrangements are there?

We computed that there are $524160$ ways to arrange the employees in the group photo of 5 persons. However, some of these arrangements only differ in the order of the employees. For example, the arrangements 

$$
\begin{align*}
(A,B,C,D,E) \\
(B,A,C,D,E)
\end{align*}
$$

are the same for the purpose of the group photo (both have the same employees, only in a different order).

For a group of 5 persons, there are $5! = 120$ ways to arrange the employees. This means that there are $524160 / 120 = 4368$ ways to arrange the employees in the group photo.

More generally, the number of ways to select $k$ elements from a set of $n$ elements, without replacement and without regard to order:

$$
\frac{n!}{k!(n-k)!} = \binom{n}{k}
$$

You may have seen this notation before. The symbol 

$$
\binom{n}{k}
$$ 

is read as "n choose k" and is called a binomial coefficient or combination. In the previous example we had $n = 16$ and $k = 5$.


In [12]:
math.comb(16, 5)

4368

In [13]:
math.factorial(16) / (math.factorial(5) * math.factorial(16 - 5))

4368.0

## Partitions

Now that the employees of the small company have agreed to ignore the order of the persons in the photos, they decide to take a group photo with 4 employees. To avoid the injustice of some employees being left out of the photo, they decide to form four groups of 4 employees. In how many ways can they form these groups?

We can approach this problem by considering the formation of groups sequentially.

- For the first group, there are $\binom{16}{4}$ ways to select four employees.
- Four persons have already been selected, so there are $\binom{12}{4}$ ways to select four employees for the second group.
- Eight persons have already been selected, so there are $\binom{8}{4}$ ways to select two students for the third group.
- And so on.

The total number of ways to form the groups is:

$$
\binom{16}{4} \times \binom{12}{4} \times \binom{8}{4}\times \binom{4}{4}
$$

We can generalize this to the case where we have a set of $n$ elements that must be partitioned into $k$ groups of sizes $n_1, n_2, \ldots, n_k$. As every element must be assigned to a group, the sum of the sizes of the groups must be equal to $n$:

$$
n_1 + n_2 + \ldots + n_k = n
$$

The general formula for the number of ways to partition a set follow the same steps as the students example, except that now the group sizes may be different.

- For the first group, there are $\binom{n}{n_1}$ ways to select $n_1$ elements.
- $n_1$ elements have already been selected, so there are $\binom{n - n_1}{n_2}$ ways to select $n_2$ elements for the second group.
- And so on.

The total number of ways to partition the set is:

$$
\binom{n}{n_1} \times \binom{n - n_1}{n_2} \times \ldots \times \binom{n - n_1 - n_2 - \ldots - n_{k-1}}{n_k}
$$

We can simplify this expression as it contains many terms that cancel out:

$$
\frac{n!}{n_1! (n - n_1)!} \times \frac{(n - n_1)!}{n_2! (n - n_1 - n_2)!} \times \frac{(n - n_1 - n_2)!}{n_3! (n - n_1 - n_2 - n_3)!} \times \ldots \times \frac{(n - n_1 - n_2 - \ldots - n_{k-1})!}{n_k! (n - n_1 - n_2 - \ldots - n_k)!}
$$

Notice that the denominator of the first term is the numerator of the second term, the denominator of the second term is the numerator of the third term, and so on. This means that all the terms cancel out except for the numerator of the first term and the denominator of the last term. The total number of ways to partition the set is:

$$
\frac{n!}{n_1! \cancel{(n - n_1)!}} \times \frac{\cancel{(n - n_1)!}}{n_2! \cancel{(n - n_1 - n_2)!}} \times \frac{\cancel{(n - n_1 - n_2)!}}{n_3! \cancel{(n - n_1 - n_2 - n_3)!}} \times \ldots \times \frac{\cancel{(n - n_1 - n_2 - \ldots - n_{k-1})!}}{n_k! (n - n_1 - n_2 - \ldots - n_k)!} = \frac{n!}{n_1! n_2! \ldots n_k!}
$$

The term in the last denominator does not cancel out but it is equal to 1, because the group sizes must sum to $n$ and $0! = 1$ (by definition). 

$$
(n - (n_1 + n_2 + \ldots + n_k))! = 0! = 1
$$

This means that the total number of ways to partition the set is:

$$
\frac{n!}{n_1! n_2! \ldots n_k!}
$$

This expression is called a multinomial coefficient and is denoted as 

$$
\binom{n}{n_1, n_2, \ldots, n_k}
$$.


## Exercises

:::{#exr-combinations}

## Password Cracking

A site asks you to generate a password with 6 characters. The password must contain only ASCII lowercase letters (a-z). What is the maximum time it would take to crack the password if the attacker tries all possible passwords (and is unlucky enough to find the password in the last attempt)? Assume that the attacker can try one billion passwords per second.

How does the answer change if the password may contain both lowercase and uppercase letters (a-z, A-Z), digits (0-9), and special characters (!@#$%^&*()_+)?

How does the answer change if the password must be exactly 14 characters long?

:::



:::{#exr-combinations}
## Number of Student Committees

Let's say that you want to form a student council with 5 members out of a class of 35 students. 

- How many different student councils can you form?
- Let's assume that the class consists of 20 women and 15 men. How many different student councils can you form if the student council must consist of 3 women and 2 men?
- Assume that two of the men have a conflict and cannot sit on the student council together.

:::

:::{#exr-power-set}
## Power Set

The power set of a set $S$ is the set of all subsets of $S$, including the empty set and $S$ itself. For a set with $n$ elements, how much elements does the power set have?

:::

:::{#exr-binomial-coefficients}
## Binomial Coefficients

Argue why the following sum of binomial coefficients for a fixed $n$ is equal to $2^n$:

$$
\sum_{k = 0}^{n} \binom{n}{k} = \binom{n}{0} + \binom{n}{1} + \binom{n}{2} + \ldots + \binom{n}{n} = 2^n
$$



:::{#exr-combinations-2}

An IT department has four lead developers and 12 junior developers. The company wants to form four teams of equal size out of all developers. How many ways can the teams be formed?

If the teams are formed at random (i.e. each group of four developers is equally likely), what is the probability that all teams include a lead developer?
:::



:::{#exr-combinations-3}

You roll three dice (6-sided) and sum the results. Which event is more probable: rolling a sum of 11 or rolling a sum of 12?
:::


In [15]:
# (Optional) Write a simulation to estimate the probabilities of the sum of three dice rolls being A) 11 and B) 12.





:::{#exr-birthdays}
## Birthdays in a Classroom

In our class of (let's say) $n$ students, what is the probability (as a function of $n$) that at least two students share the same birthday? For simplicity, assume that there are 365 days in a year and that each student is equally likely to be born on any day of the year. What is the smallest value of $n$ for which the probability is greater than 1/2?

:::

:::{#exr-poker}
## Full House in Poker

![](https://as2.ftcdn.net/v2/jpg/03/41/80/33/1000_F_341803398_DPfP99KnvQChRNcC1kuFdEEElQUPxMm0.jpg){style="width: 300px"}

You play a game of poker with a standard deck of 52 cards. A full house is a hand that contains three cards of one rank and a pair of another rank.
You are dealt a hand from a well-shuffled deck of cards. What is the probability that you are dealt a full house?

:::