project:
  type: book
  output-dir: _site

book:
  title: "Basic Statistics 2024"
  author: "Boyko Amarov"
  date: "10/01/2024"


bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex

editor: visual

profile:
  default: development

execute: 
  enabled: true
